<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * AppartenirRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppartenirRepository extends \Doctrine\ORM\EntityRepository
{
}
