<?php

namespace AppBundle\Repository;

/**
 * commentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class commentaireRepository extends \Doctrine\ORM\EntityRepository
{
}
