<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\CompteRendu;

/**
 * CompteRenduRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompteRenduRepository extends \Doctrine\ORM\EntityRepository
{
	public function insertcompteRenduFull($chemin, $idProjet){

		$user = new Utilisateur();
		$user->setChemin($chemin);
		$user->setIdProjet($idProjet);

		$em = $this->getDoctrine()->getManager();
	    $em->persist($product);
	    $em->flush();
	    
	}

}
