<?php

namespace AppBundle\Repository;

/**
 * entrepriseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class entrepriseRepository extends \Doctrine\ORM\EntityRepository
{
}
