<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;
/**
 * PrioriteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrioriteRepository extends \Doctrine\ORM\EntityRepository
{
}
