<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\Projet;
/**
 * projetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetRepository extends \Doctrine\ORM\EntityRepository
{

	public function insertProjetFull($nom, $projetExtOuInt, $ydaysPerso, $statusEvaluations, $archiver, $idUtilisateurs, $idUtilisateurs1, $idEntreprises){

		$user = new Utilisateur();
		$user->setNom($nom);
		$user->setProjetExtOuInt($prenom);
		$user->setYdaysPerso($classeOuFonction);
		$user->setStatusEvaluations($role);
		$user->setArchiver($projet);
		$user->setIdUtilisateurs($mail);
		$user->setIdUtilisateurs1($tel);
		$user->setIdEntreprises($slackName);
		$em = $this->getDoctrine()->getManager();
	    $em->persist($product);
	    $em->flush();
	    
	}

	//Met le projet en mode archivé
	public function updateArchiveProjet($idProjet){

		$repository = $this->getDoctrine()->getManager()->getRepository('AppBundle:Projet');

		$projet = $repository->find($idProjet);
		$projet->setArchiver(true); 
		$em = $this->getDoctrine()->getManager();
		$entityManager->persist($projet);
		$entityManager->flush();
	}

	//ajout chef de projet
	public function updateChefDeProjet($idProjet, $idUser){

		$repository = $this->getDoctrine()->getManager()->getRepository('AppBundle:Projet');

		$projet = $repository->find($idProjet);
		$projet->setIdUtilisateurs($idUser); 
		$em = $this->getDoctrine()->getManager();
		$entityManager->persist($projet);
		$entityManager->flush();
	}

	//ajout Helper
	public function updatetHelper($idProjet, $idUser){

		$repository = $this->getDoctrine()->getManager()->getRepository('AppBundle:Projet');

		$projet = $repository->find($idProjet);
		$projet->setIdUtilisateurs1($idUser); 
		$em = $this->getDoctrine()->getManager();
		$entityManager->persist($projet);
		$entityManager->flush();
	}

	//ajout entreprise
	public function updateEntreprise($idProjet, $idEntreprise){

		$repository = $this->getDoctrine()->getManager()->getRepository('AppBundle:Projet');

		$projet = $repository->find($idProjet);
		$projet->setIdEntreprises($idUser); 
		$em = $this->getDoctrine()->getManager();
		$entityManager->persist($projet);
		$entityManager->flush();
	}

	
}
