<?php

namespace AppBundle\Repository;

/**
 * rapportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class rapportRepository extends \Doctrine\ORM\EntityRepository
{
}
