<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * SituerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SituerRepository extends \Doctrine\ORM\EntityRepository
{
}
