<?php

namespace AppBundle\Repository;

/**
 * statut_usrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class statut_usrRepository extends \Doctrine\ORM\EntityRepository
{
}
