<?php

namespace AppBundle\Repository;

/**
 * StatusEvaluationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatusEvaluationRepository extends \Doctrine\ORM\EntityRepository
{
}
