<?php

namespace AppBundle\Repository;

/**
 * utilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class utilisateurRepository extends \Doctrine\ORM\EntityRepository
{
}
