# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt # encodage des données dans la table

    # création des différents roles pour attribuer des droits au utilisateurs
    role_hierarchy:
        ROLE_ETUDIANT:      ROLE_USER
        ROLE_CHEF:      [ROLE_ETUDIANT, ROLE_USER]
        ROLE_HELPER:        ROLE_HELPER
        ROLE_ADMIN:       [ROLE_HELPER, ROLE_CHEF]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]


    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
            main:
                pattern: ^/
                form_login:
                    provider: fos_userbundle
                    csrf_token_generator: security.csrf.token_manager
                    login_path: /
                logout: true
                anonymous:    true


    # url dédié, demandant certains droits
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: ROLE_SUPER_ADMIN }
        - { path: ^/resetting, role: ROLE_HELPER }
        - { path: ^/admin, role: ROLE_ADMIN }
        - { path: ^/dashboard, role: ROLE_USER }


